version: '3'
services:
  #  web:
  #    build: .
  #    command: go run main.go
  #    ports:
  #      - 8081:8081
  #    networks:
  #      - octopus-net

  #  redis:
  #    image: redis:latest

  mysql:
    network_mode: "bridge"
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: 'test'
      MYSQL_PASS: '123456'
      MYSQL_DATABASE: octopus
      TZ: Asia/Shanghai
    volumes:
      - "./conf/mysql/db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./conf/init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
