version: '3'
services:
#  master:
#    build: .
#    command: go run main.go
#    ports:
#      - "8082:8082"
#    networks:
#      - octopus-net
#
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#      - "8081:8081"
#    depends_on:
#      - "master"
#    volumes:
#      - "$PWD/conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
#      - "$PWD/www:/user/share/nginx/www"
#    networks:
#      - octopus-net

  redis:
    image: redis:latest
    volumes:
      - "$PWD/conf/redis/data:/data"
    ports:
      - "6380:6379"
    network_mode: "bridge"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: 'test'
      MYSQL_PASS: '123456'
      MYSQL_DATABASE: octopus
      TZ: Asia/Shanghai
    volumes:
      - "$PWD/conf/mysql/db:/var/lib/mysql"
      - "$PWD/conf/mysql/my.cnf:/etc/my.cnf"
      - "$PWD/conf/mysql/init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
    network_mode: "bridge"


#networks:
#  octopus-net:
#    driver: bridge
